spring:
  application:
    name: AI_Code_Generator

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  ai:
    openai:
      api-key: ${OPEN_ROUTER}
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          model: poolside/laguna-xs.2:free
          temperature: 0.0


jwt:
  secret-key: ${JWT_SECRET}

stripe:
  api:
    secret: ${STRIPE_SECRET}
  webhook:
    secret: ${WEBHOOK_SECRET}

client:
  url: ${CLIENT_URL}

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG
    com.springboot.AI_Code_Generator: DEBUG
    org.springframework.security: DEBUG

minio:
  url: http://localhost:9000          # or minio:9000 if inside docker network
  access-key: ${MINIO_USER}
  secret-key: ${MINIO_PWD}
  project-bucket: projects